version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: eatrryy
    networks:
      - mydb
    volumes:
      - database-postgres:/var/lib/postgresql/data
    

  app:
    image: eatry
    build: .
    restart: on-failure
    depends_on:
      - postgres
    networks:
      - mydb
    ports:
      - "8000:8000"
    environment:
      DB_HOST: postgres
      DB_PASSWORD: 123456

volumes: 
  database-postgres:     
networks:
  mydb:
    driver: bridge

